# Site settings
title: "Leonel A Alfonso"
email: andresad13@gmail.com
description: "Leonel Alfonso blog"
baseurl: ""
url: "http://andresad13.github.io"
title_description: "develop and design"
title_image: "https://s.gravatar.com/avatar/99478936f50db27dfc0c40a09a1eda2e?s=80"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/andresad13
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: andresad13
github_username:  andresad13
linkedin_link: https://www.linkedin.com/pub/leonel-alfonso/b9/975/357
google_plus_link: https://plus.google.com/u/0/106982303984702409074
stackoverflow_link: http://stackoverflow.com/users/5104430/leonel-andr%C3%A9s-alfonso-duarte

# Footer
footer_left: "Made by @andresad13"
footer_right: "love, passion ,code"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
